baseurl = "/"
relativeurls = true
publishDir = "public"
title = "Max's Notes"
author = "Max Kovalovs"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Max's Coding Notes"

[[menu.main]]
    name = "CV"
    url = "maxkovalovs.us"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/max-kov"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = ""
    weight = 3
